# Generated by Django 5.2.15 on 2026-06-26 15:53

import blog.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the name. Automatically generated.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description for the category page.')),
                ('image', models.ImageField(blank=True, help_text='An optional image for the category.', null=True, upload_to='category_images/')),
                ('indexable', models.BooleanField(default=False, help_text="If unchecked, adds 'noindex, nofollow' for this page.")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the name. Automatically generated.', max_length=120, unique=True)),
                ('indexable', models.BooleanField(default=False, help_text="If unchecked, adds 'noindex, nofollow' for this page.")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post.', max_length=250)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the title. Must be unique.', max_length=250, unique=True)),
                ('body', ckeditor.fields.RichTextField(help_text='The main content of the post. Use the rich text editor.')),
                ('featured_image', models.ImageField(blank=True, help_text='An optional main image for the post.', null=True, upload_to='post_images/')),
                ('indexable', models.BooleanField(default=True, help_text="If unchecked, adds 'noindex, nofollow' for this page.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], db_index=True, default='DF', max_length=2)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title: Appears in the browser tab and search results. Keep it under 60 characters.', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description: A brief summary for search engines. Keep it under 160 characters.')),
                ('short_answer', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The FAQ question.', max_length=255)),
                ('answer', ckeditor.fields.RichTextField(help_text='The answer to the FAQ question.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.post')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The unique key for the shortcode (e.g., 'circular_number'). Do not include brackets.", max_length=50)),
                ('value', models.CharField(blank=True, help_text='The text value for this placeholder.', max_length=250, null=True)),
                ('image', models.ImageField(blank=True, help_text="The image value for this placeholder. Will be saved in a folder named after the post's slug.", null=True, upload_to=blog.models.get_placeholder_image_path)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image.', max_length=150, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='blog.post')),
            ],
            options={
                'unique_together': {('post', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-updated_at'], name='blog_post_updated_261a59_idx'),
        ),
    ]
