# Generated by Django 5.2.15 on 2026-06-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_demo_typography_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], db_index=True, default='DF', max_length=2),
        ),
    ]
