# Generated by Django 5.2.15 on 2026-06-21 07:49

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Marketing Glossary', max_length=160)),
                ('intro', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=180)),
                ('json_ld_enabled', models.BooleanField(default=True)),
                ('faq_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Glossary Page Config',
                'verbose_name_plural': 'Glossary Page Config',
            },
        ),
        migrations.CreateModel(
            name='GlossaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='glossary_gl_slug_a08cdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlossaryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='glossary.glossarypageconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_definition', models.CharField(max_length=250)),
                ('long_definition', models.TextField(blank=True)),
                ('synonyms', models.CharField(blank=True, max_length=500)),
                ('acronym', models.CharField(blank=True, max_length=300)),
                ('example', models.TextField(blank=True)),
                ('use_cases', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10)),
                ('review_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='glossary.glossarycategory')),
                ('related_terms', models.ManyToManyField(blank=True, to='glossary.glossaryterm')),
            ],
            options={
                'ordering': ['term'],
                'indexes': [models.Index(fields=['slug'], name='glossaryterm_slug_idx'), models.Index(fields=['status'], name='glossaryterm_status_idx'), models.Index(fields=['category'], name='glossaryterm_category_idx'), models.Index(django.db.models.functions.text.Lower('term'), name='glossaryterm_term_lower_idx')],
            },
        ),
    ]
