# Generated by Django 5.2.15 on 2026-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_remove_glossaryterm_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryfaq',
            name='page',
        ),

        migrations.RemoveField(
            model_name='glossarypageconfig',
            name='faq_enabled',
        ),
        migrations.RemoveField(
            model_name='glossarypageconfig',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='glossarypageconfig',
            name='json_ld_enabled',
        ),
        migrations.RemoveField(
            model_name='glossarypageconfig',
            name='title',
        ),
        migrations.AlterField(
            model_name='glossarypageconfig',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='GlossaryFAQ',
        ),
    ]
