# Generated by Django 5.2.15 on 2026-06-21 15:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tldr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('comparison_table', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='top/')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top 10 Profile',
                'verbose_name_plural': 'Top 10 Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_placeholders/')),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='top10s.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tools/')),
                ('description', ckeditor.fields.RichTextField()),
                ('feature_label', models.CharField(default='Key Features', max_length=100)),
                ('features', models.TextField()),
                ('pros_label', models.CharField(default='Pros', max_length=100)),
                ('pros', models.TextField()),
                ('personal_review', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='top10s.profiles')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
