# Generated by Django 5.2.15 on 2026-06-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
