# Generated by Django 5.2.15 on 2026-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10s', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={},
        ),
        migrations.AlterField(
            model_name='profiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='feature_label',
            field=models.CharField(default='Key Feature', max_length=100),
        ),
    ]
